<?php

return [
    [
        'name' => 'debugmode',
        'title' => '调试模式',
        'type' => 'radio',
        'content' => [
            'Y' => '开启',
            'N' => '关闭',
        ],
        'value' => 'Y',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ddcorpId',
        'title' => '钉钉corpId',
        'type' => 'string',
        'content' => [],
        'value' => 'ding284e04cdd0a47af0f2c783f7214b6d69',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ddappid',
        'title' => '钉钉appid',
        'type' => 'string',
        'content' => [],
        'value' => 'dingoahksusk6exvgkwlqe',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ddappsecret',
        'title' => '钉钉appsecret',
        'type' => 'string',
        'content' => [],
        'value' => 'IhwAwt8vDF2AKwyOoAzUHGqddCfL-uMFBrf5JDHiHMsgfcwvsurdCsmE4ySwkijT',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ddh5agentid',
        'title' => '钉钉H5 AgentId',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ddh5appid',
        'title' => '钉钉H5 appid',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ddh5appsecret',
        'title' => '钉钉H5 appsecret',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ddnonceStr',
        'title' => '钉钉随机串nonceStr',
        'type' => 'string',
        'content' => [],
        'value' => 'abcd123',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isdduseropenadmin',
        'title' => '钉钉通讯录同步开通管理员',
        'type' => 'radio',
        'content' => [
            'N' => '不开通',
            'Y' => '开通',
        ],
        'value' => 'Y',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ddadmindefaultroles',
        'title' => '默认创建管理员的角色',
        'type' => 'string',
        'content' => [],
        'value' => '2,3',
        'rule' => '',
        'msg' => '',
        'tip' => '角色组ID,多个以逗号分隔',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isdduseropendepart',
        'title' => '钉钉通讯录同步到本地组织架构',
        'type' => 'radio',
        'content' => [
            'N' => '不开通',
            'Y' => '开通<span style="color:red">(需要安装插件[后台管理账号增强])<span>',
        ],
        'value' => 'N',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'portletwebtitle',
        'title' => '钉钉移动门户标题',
        'type' => 'string',
        'content' => [],
        'value' => '钉钉对接套件',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
